version: '3.8'

services:
  app:
    build:
      context: .
      args:
        - no-cache: "true"
    container_name: my-python-app
    ports:
      - "3000:3000"
    volumes:
      - ./downloads:/app/downloads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=bot.py
      - PORT=3000
    network_mode: "host"
    restart: on-failure
