version: '3.8'

services:
  web:
    build: .
    container_name: woodcraft-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app  
    networks:
      - web-network
    restart: always  

networks:
  web-network:
    driver: bridge
